name: CI-CD

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.5

      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
    
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.4.0
        with:
          context: .
          push: true
          tags: 
            ${{secrets.DOCKERHUB_USER}}/site-nginx-test-cicd:v1
            ${{secrets.DOCKERHUB_USER}}/site-nginx-test-cicd:latest

      - name: Logout do Docker Hub
        run: docker logout

      
